### ISSUE TITLE
Formato de data ao adicionar conta

### ISSUE THREAD

**Issue by italo-batista** [italo-batista/SIGA#49]
Em adicionar uma nova conta (painel de gerência), adequar formata de data para 'yyyy-mm-dd', que é o padrão utilizado pelo mongodb.

**Comment by gabrielmla** [comment]
Eu acho que isso seja de certa importância, porém me enganei. Eu pensei que era por causa disso que a data de pagamento não estava sendo salva, mas acredito que seja por causa de que no calendar esteja salvando na conta da seguinte forma: ctrl.conta.data, quando o field na verdade se chama dataDePagamento. Resumindo, não estava salvando a data de pagamento e pensei que era por causa do formato, mas acho que é no html.

**Comment by italo-batista** [comment]
Eu vim ver aqui.. Ele está setando uma data no banco, mas sempre é uma data default (a do dia que cria a conta pelo painel). Vou ajeitar isso depois.
![captura de tela de 2017-08-24 17-47-19](https://user-images.githubusercontent.com/13472668/29688106-ec38cf90-88f4-11e7-8ec7-62bd19a2db2c.png)

**Comment by italo-batista** [comment]
Done.

![captura de tela de 2017-08-24 18-16-02](https://user-images.githubusercontent.com/13472668/29689088-4fea65be-88f8-11e7-9fbe-8771e098f2f6.png)
